force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Total_Members__c.field-meta.xml
<CustomField>
    <fullName>Total_Members__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Group__c/User_Group__c.object-meta.xml
<CustomObject>
    <label>User Group</label>
    <nameField>
        <displayFormat>UG-{000000}</displayFormat>
        <label>User Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Group__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>User Groups</relationshipLabel>
    <relationshipName>User_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserGroupHandler.cls
public class UserGroupHandler {
    public static void countGroupMembers(Id GroupId){
        AggregateResult results = [Select Count(Id) From User_Group__c Where Group__c = :GroupId];
        Integer userGroupCount = (Integer)results.get('expr0');
        
        Group__c usrGrp = [Select Id From Group__c Where Id = :GroupId];
        usrGrp.Total_Members__c = userGroupCount;
        update usrGrp;
        
    }
}